version: '3'

services:
  postgres:
      container_name: postgres
      image: postgres
      volumes:
        - postgres-volume:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  rabbit:
    container_name: rabbitmq
    image: "rabbitmq:management"
    volumes:
      - 'rabbitmq-volume:/var/lib/rabbitmq/mnesia/'
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
      
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-volume:/data
    ports:
      - "6379:6379"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"   

volumes:
  postgres-volume:
  redis-volume:
  rabbitmq-volume: